apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: emp
  labels:
    app: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
        
    spec:
      containers:
        - name: frontend
          image: verbose2001/emp_frontend:latest
          ports:
            - containerPort: 3000