apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: emp

spec:
  ports:
    - name: frontend
      port: 80
      targetPort: 3000
      nodePort: 30001
  
  selector:
    app: frontend
  type: NodePort
