apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: emp

spec:
  ports:
    - name: backend
      port: 8080
      targetPort: 8080
  
  selector:
    app: backend
  type: ClusterIP
