apiVersion: apps/v1
kind: Secret
metadata:
  name: {{ .Values.cluster-secret.name | default "cluster-secret" }}
  namespace: {{ .Values.cluster-secret.namespace | default "helm-test" }}
type: Opaque
stringData:
  CIPHER_KEY: {{ .Values.cluster-secret.CIPHER_KEY }}
  DB_PASSWORD: {{ .Values.cluster-secret.DB_PASSWORD }}
  SECRET_TOKEN: {{ .Values.cluster-secret.SECRET_TOKEN }}
  PLATFORM_KEY: {{ .Values.cluster-secret.PLATFORM_KEY }}
  