apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.events-bridge.name | default "events-bridge" }}
  namespace: {{ .Values.events-bridge.namespace | default "helm-test" }}

spec:
  selector:
    matchLabels:
      app: {{ .Values.events-bridge.name | default "events-bridge" }}
  template:
    metadata:
      labels:
        app: {{ .Values.events-bridge.name | default "events-bridge" }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.events-bridge.imagePullSecrets.name | default "jfrog-secret" }}
      {{- include "Node_affinity" . | nindent 6 }}
      volumes:
        - name: {{ .Values.events-bridge.volumeName | default "secret-volume" }}
          secret:
            secretName: {{ .Values.events-bridge.secretName | default "clustersecrets" }}
      dnsPolicy: ClusterFirst
      containers:
        - name: {{ .Values.events-bridge.name | default "events-bridge" }}
          {{- include "securityContext" . | nindent 10 }}
          image: {{ .Values.events-bridge.image }}
          imagePullPolicy: {{ .Values.events-bridge.imagePullPolicy }}
          volumeMounts:
            {{ toYaml .Values.events-bridge.volumeMounts | nindent 12 }}
          {{- with .Values.events-bridge.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- else }}
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.events-bridge.containerPort | default 8083 }}
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.events-bridge.containerPort | default 8083 }}
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 10
          ports:
            - containerPort: {{ .Values.events-bridge.containerPort | default 8083 }}
          envFrom:
            {{ toYaml .Values.events-bridge.envFrom | nindent 12 }}
          env:
            - name: PORT
              value: "8083"