apiVersion: apps/v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.minio-pvc.name | default "idp-minio-pvc" }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.minio-pvc.resources }}
  resources:
    {{ toYaml . | nindent 4 }}
  {{- else }}
  resources:
    requests:
      storage: 100Gi
  {{- end }}
  storageClassName: {{ .Values.minio-pvc.storageClassName | default "standard-rwo" }}