apiVersion: apps/v1
kind: Pod
metadata:
  name: {{ .Values.miniotransferpod.name | default "task-pv-pod" }}
  namespace: {{ .Values.miniotransferpod.namespace | default "helm-test" }}

spec:
  {{- include "Node_affinity" . | nindent 2 }}
  {{- with .Values.miniotransferpod.volumes }}
  volumes:
    {{- toYaml . | nindent 2 }}
  {{- end }}

  containers:
    - name: {{ .Values.miniotransferpod.name | default "miniotransferpod" }}
      image: {{ .Values.miniotransferpod.image }}
      {{- with .Values.miniotransferpod.resources }}
      resources:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- include "probes" . | nindent 6 }}
      {{- with .Values.miniotransferpod.ports }}
      ports:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.miniotransferpod.volumeMounts }}
      volumeMounts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
